# Generated by Django 4.2.2 on 2023-09-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nechuwebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mybg/')),
                ('title1', models.CharField(max_length=500)),
                ('title2', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Background_image6',
        ),
    ]
